server:
  port: 8080
spring:
  application:
    name: memory-chat
  main:
    allow-circular-references: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-xxx}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o
          temperature: 0.0
      embeddings:
        options:
          model: text-embedding-3-small
      image:
        options:
          model: dall-e-3
          size: 1792x1024
      temperature: 0.0
  redis:
    host: 127.0.0.1
    port: 6379

wechat:
  app-version: 1.0
  login-title: 微信登录
  base-path:  ${user.dir}${file.separator}temp
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.62 Safari/537.36
  special-user: filehelper, weibo,qqmail, fmessage, tmessage, qmessage, qqsync, floatbottle, lbsapp, shakeapp, medianote,qqfriend, readerapp, blogapp, facebookapp, masssendapp, meishiapp, feedsapp, voip,blogappweixin, brandsessionholder, weixinreminder, officialaccounts, wxitil,notification_messages, wxid_novlwrv3lqwv11, gh_22b87fa7cb3c, userexperience_alarm
  fuzz-up-avatar: false

github:
  accessToken:
  owner:
  repo:
  path:
  addMessage: add img
  delMessage: del img
  apiCreatePost: https://api.github.com/repos/%s/%s/contents/%s
  branch:
  email:
  accept: application/vnd.github+json
  contentType: application/json

serp:
  apiKey:
  baseUrl: https://serpapi.com/search

emoji:
  directory: ${user.dir}${file.separator}temp${file.separator}emoji${file.separator}

es:
  url: 127.0.0.1
  port: 9200

reflection:
  tokenLimit: 1000

chatMemoryIndex: chat_memory
maxMsgToken: 50000

weather:
  key: xxx

wolframalpha:
  key: xxx

