server:
  port: 8080
spring:
  application:
    name: memory-chat
  main:
    allow-circular-references: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:sk-xxx}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o
          temperature: 0.0
wechat:
  app-version: 1.0
  login-title: 微信登录
  base-path:  ${user.dir}/temp
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.62 Safari/537.36
  special-user: filehelper, weibo,qqmail, fmessage, tmessage, qmessage, qqsync, floatbottle, lbsapp, shakeapp, medianote,qqfriend, readerapp, blogapp, facebookapp, masssendapp, meishiapp, feedsapp, voip,blogappweixin, brandsessionholder, weixinreminder, officialaccounts, wxitil,notification_messages, wxid_novlwrv3lqwv11, gh_22b87fa7cb3c, userexperience_alarm
  fuzz-up-avatar: false

github:
  accessToken:
  owner:
  repo:
  path:
  addMessage: add img
  delMessage: del img
  apiCreatePost: https://api.github.com/repos/%s/%s/contents/%s
  branch:
  email:
  accept: application/vnd.github+json
  contentType: application/json
